# This manifest advertises external IPs on all network interfaces, creates an IPAM pool
# for assigning addresses and finally deploys an ingress controller using the first address of
# the pool. The first two configurations are necessary for enabling load balancers to be reachable
# from your network. The ingressController is optional and can be commented / removed.
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: external
  namespace: kube-system
spec:
  externalIPs: true
  loadBalancerIPs: true
  serviceSelector:
    matchLabels:
      loadbalancer-type: external
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: external-pool
  namespace: kube-system
spec:
  serviceSelector:
    matchLabels:
      loadbalancer-type: external
  blocks:
    - start: 192.168.0.130
      stop: 192.168.0.149