#! /bin/bash
### Note: The manifest that is generated by this script contains sensitive
###       information. If you commit it to a git repo, make sure it is private.

# Templates the https://kubernetes-sigs.github.io/metrics-server/ helm chart using the 'metrics-values.yaml' values file in this 
# directory, saving the output values to an .env/k8s-metrics-manifest.yml.
# If you plan on installing Kubernetes Metrics Server, make sure to set 'talos_cluster.metrics_server_enabled=true' 
# in your .env/{your_environment}.tfvars file after templating the charts.
# Note: There's an issue with the current version of the helm charts that neglects to add the namespace (kube-system)
#       to the metrics-server secret declaration. This script patches it using a kustomization before outputing to the .env directory.
set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "${SCRIPT_DIR}"

TEMPLATE_VALUES="metrics-values.yaml"
MANIFEST_FILE="k8s-metrics-manifest.yml"
OUPUT_MANIFEST="../.env/${MANIFEST_FILE}"

tmp_metrics_dir=$(mktemp -d "metrics.XXXXXXXXXXXXXXXX" -p .)
trap 'rm -rf "$tmp_metrics_dir"' EXIT
tmp_manifest="${tmp_metrics_dir}/k8s-metrics-manifest.yml"

# echo "### Adding Kubernetes Metrics Server Helm Repository ###"
helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/
helm repo update

echo "### Creating Kubernetes Metrics Server Manifest ###"
helm template metrics-server metrics-server/metrics-server \
    --namespace kube-system -f "${TEMPLATE_VALUES}" \
    > "${tmp_metrics_dir}/${MANIFEST_FILE}"

echo ""
echo "### Patching generated manifest to use kube-system namespace ###"
# Create kustomization to apply kube-system namespace to all resources
echo -n "
# built by ./refresh.sh
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - ${MANIFEST_FILE}" > "${tmp_metrics_dir}/kustomization.yaml"
kubectl apply -k "${tmp_metrics_dir}" --dry-run=client -oyaml > "${OUPUT_MANIFEST}"

echo ""
echo "### Templating Complete ###"
echo "Manifest file saved to: $(realpath "${OUPUT_MANIFEST}")."
echo "Make sure to enable the 'talos_cluster.metrics_server_enabled' setting in your tfvars file to enable the installation of Kubernetes Metrics Server."